apiVersion: 1

datasources:
  - name: Invest SQLite
    type: frser-sqlite-datasource
    uid: invest_sqlite
    access: proxy
    isDefault: true
    jsonData:
      path: /data/stock_data.db
      pathPrefix: 'file:'
      pathOptions: mode=ro
      attachLimit: 0
